### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by ZalaMandip** [TooSchoolForCool/EddieBot-ROS#2]
I am trying use the driver on my Ubuntu 20.04 machine with ros noetic. I only need the basic driver (`eddiebot_bringup` pkg) , since i am working on a project that requires developing other features. The build was successful but upon launching the driver node i get the following error
````
[ERROR] [1652178221.866641528]: ERROR: NO PARALLAX EDDIE ROBOT IS CONNECTED.
[ERROR] [1652178221.866768224]: DIST
[ERROR] [1652178221.956140268]: ERROR: NO PARALLAX EDDIE ROBOT IS CONNECTED.
[ERROR] [1652178221.956265498]: ACC 64
[ERROR] [1652178221.956872089]: ERROR: Failed to set acceleration rate to 100
[ERROR] [1652178222.066463971]: ERROR: NO PARALLAX EDDIE ROBOT IS CONNECTED.
[ERROR] [1652178222.066575092]: DIST
[ERROR] [1652178222.266166004]: ERROR: NO PARALLAX EDDIE ROBOT IS CONNECTED.
[ERROR] [1652178222.266260922]: DIST
[ERROR] [1652178222.466058990]: ERROR: NO PARALLAX EDDIE ROBOT IS CONNECTED.
[ERROR] [1652178222.466152999]: DIST

```` 
i also checked for the serial device name. But it seems to be right. I am not sure what is causing this issue. Any suggestion would be helpful. Thanks in advance

**Comment by TooSchoolForCool** [comment]
You need an actual PARALLAX EDDIE Robot connected to your desktop/laptop when running the `eddiebot_bringup` pkg.

**Comment by ZalaMandip** [comment]
Thanks for the response.

As you mentioned the Eddibot is actually connected to my laptop using USB cable. And I'm only launching the driver node. But unfortunately the node fails to connect to the bot.

**Comment by TooSchoolForCool** [comment]
1. You need to have EddieBot firmware properly installed and configured.
2. Check if the program have permission to access to the USB connected device, e.g., `/dev/xxx`. Usually files under `/dev` require root to read and write. You can grant other user accessibility via command `sudo chmod xxx /dev/xxx`.

**Comment by ZalaMandip** [comment]
Thanks for the help. its working properly now.
